// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (
  image_id, original_filename, thumbnail_key, web_key, original_key,
  thumbnail_size, web_size, original_size, width, height, uploaded_by, exif
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, image_id, original_filename, thumbnail_key, web_key, original_key, thumbnail_size, web_size, original_size, width, height, uploaded_by, uploaded_at, published, moderation_status, date_type, exact_date, start_date, end_date, approx_year, approx_month, occasion_category, occasion_name, exif
`

type CreateImageParams struct {
	ImageID          string                `json:"image_id"`
	OriginalFilename sql.NullString        `json:"original_filename"`
	ThumbnailKey     sql.NullString        `json:"thumbnail_key"`
	WebKey           sql.NullString        `json:"web_key"`
	OriginalKey      sql.NullString        `json:"original_key"`
	ThumbnailSize    sql.NullInt64         `json:"thumbnail_size"`
	WebSize          sql.NullInt64         `json:"web_size"`
	OriginalSize     sql.NullInt64         `json:"original_size"`
	Width            sql.NullInt32         `json:"width"`
	Height           sql.NullInt32         `json:"height"`
	UploadedBy       uuid.NullUUID         `json:"uploaded_by"`
	Exif             pqtype.NullRawMessage `json:"exif"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage,
		arg.ImageID,
		arg.OriginalFilename,
		arg.ThumbnailKey,
		arg.WebKey,
		arg.OriginalKey,
		arg.ThumbnailSize,
		arg.WebSize,
		arg.OriginalSize,
		arg.Width,
		arg.Height,
		arg.UploadedBy,
		arg.Exif,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.OriginalFilename,
		&i.ThumbnailKey,
		&i.WebKey,
		&i.OriginalKey,
		&i.ThumbnailSize,
		&i.WebSize,
		&i.OriginalSize,
		&i.Width,
		&i.Height,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Published,
		&i.ModerationStatus,
		&i.DateType,
		&i.ExactDate,
		&i.StartDate,
		&i.EndDate,
		&i.ApproxYear,
		&i.ApproxMonth,
		&i.OccasionCategory,
		&i.OccasionName,
		&i.Exif,
	)
	return i, err
}

const createImagePerson = `-- name: CreateImagePerson :one
INSERT INTO image_people (image_id, name) VALUES ($1, $2) RETURNING id, image_id, name
`

type CreateImagePersonParams struct {
	ImageID uuid.UUID `json:"image_id"`
	Name    string    `json:"name"`
}

func (q *Queries) CreateImagePerson(ctx context.Context, arg CreateImagePersonParams) (ImagePerson, error) {
	row := q.db.QueryRowContext(ctx, createImagePerson, arg.ImageID, arg.Name)
	var i ImagePerson
	err := row.Scan(&i.ID, &i.ImageID, &i.Name)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const deleteImagePeople = `-- name: DeleteImagePeople :exec
DELETE FROM image_people WHERE image_id = $1
`

func (q *Queries) DeleteImagePeople(ctx context.Context, imageID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteImagePeople, imageID)
	return err
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, image_id, original_filename, thumbnail_key, web_key, original_key, thumbnail_size, web_size, original_size, width, height, uploaded_by, uploaded_at, published, moderation_status, date_type, exact_date, start_date, end_date, approx_year, approx_month, occasion_category, occasion_name, exif FROM images WHERE id = $1 LIMIT 1
`

func (q *Queries) GetImageByID(ctx context.Context, id uuid.UUID) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByID, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.OriginalFilename,
		&i.ThumbnailKey,
		&i.WebKey,
		&i.OriginalKey,
		&i.ThumbnailSize,
		&i.WebSize,
		&i.OriginalSize,
		&i.Width,
		&i.Height,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Published,
		&i.ModerationStatus,
		&i.DateType,
		&i.ExactDate,
		&i.StartDate,
		&i.EndDate,
		&i.ApproxYear,
		&i.ApproxMonth,
		&i.OccasionCategory,
		&i.OccasionName,
		&i.Exif,
	)
	return i, err
}

const getImageByImageID = `-- name: GetImageByImageID :one
SELECT id, image_id, original_filename, thumbnail_key, web_key, original_key, thumbnail_size, web_size, original_size, width, height, uploaded_by, uploaded_at, published, moderation_status, date_type, exact_date, start_date, end_date, approx_year, approx_month, occasion_category, occasion_name, exif FROM images WHERE image_id = $1 LIMIT 1
`

func (q *Queries) GetImageByImageID(ctx context.Context, imageID string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByImageID, imageID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.OriginalFilename,
		&i.ThumbnailKey,
		&i.WebKey,
		&i.OriginalKey,
		&i.ThumbnailSize,
		&i.WebSize,
		&i.OriginalSize,
		&i.Width,
		&i.Height,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Published,
		&i.ModerationStatus,
		&i.DateType,
		&i.ExactDate,
		&i.StartDate,
		&i.EndDate,
		&i.ApproxYear,
		&i.ApproxMonth,
		&i.OccasionCategory,
		&i.OccasionName,
		&i.Exif,
	)
	return i, err
}

const listImagePeople = `-- name: ListImagePeople :many
SELECT id, image_id, name FROM image_people WHERE image_id = $1 ORDER BY name
`

func (q *Queries) ListImagePeople(ctx context.Context, imageID uuid.UUID) ([]ImagePerson, error) {
	rows, err := q.db.QueryContext(ctx, listImagePeople, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImagePerson{}
	for rows.Next() {
		var i ImagePerson
		if err := rows.Scan(&i.ID, &i.ImageID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImages = `-- name: ListImages :many
SELECT id, image_id, original_filename, thumbnail_key, web_key, original_key, thumbnail_size, web_size, original_size, width, height, uploaded_by, uploaded_at, published, moderation_status, date_type, exact_date, start_date, end_date, approx_year, approx_month, occasion_category, occasion_name, exif FROM images
WHERE ($1::text IS NULL OR occasion_category = $1::text)
ORDER BY uploaded_at DESC
LIMIT $3 OFFSET $2
`

type ListImagesParams struct {
	OccasionCategory sql.NullString `json:"occasion_category"`
	Off              int32          `json:"off"`
	Lim              int32          `json:"lim"`
}

func (q *Queries) ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImages, arg.OccasionCategory, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ImageID,
			&i.OriginalFilename,
			&i.ThumbnailKey,
			&i.WebKey,
			&i.OriginalKey,
			&i.ThumbnailSize,
			&i.WebSize,
			&i.OriginalSize,
			&i.Width,
			&i.Height,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.Published,
			&i.ModerationStatus,
			&i.DateType,
			&i.ExactDate,
			&i.StartDate,
			&i.EndDate,
			&i.ApproxYear,
			&i.ApproxMonth,
			&i.OccasionCategory,
			&i.OccasionName,
			&i.Exif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImage = `-- name: UpdateImage :one
UPDATE images SET
  published         = COALESCE($1, published),
  date_type         = COALESCE($2, date_type),
  exact_date        = COALESCE($3, exact_date),
  start_date        = COALESCE($4, start_date),
  end_date          = COALESCE($5, end_date),
  occasion_category = COALESCE($6, occasion_category),
  occasion_name     = COALESCE($7, occasion_name)
WHERE id = $8
RETURNING id, image_id, original_filename, thumbnail_key, web_key, original_key, thumbnail_size, web_size, original_size, width, height, uploaded_by, uploaded_at, published, moderation_status, date_type, exact_date, start_date, end_date, approx_year, approx_month, occasion_category, occasion_name, exif
`

type UpdateImageParams struct {
	Published        sql.NullBool   `json:"published"`
	DateType         sql.NullString `json:"date_type"`
	ExactDate        sql.NullTime   `json:"exact_date"`
	StartDate        sql.NullTime   `json:"start_date"`
	EndDate          sql.NullTime   `json:"end_date"`
	OccasionCategory sql.NullString `json:"occasion_category"`
	OccasionName     sql.NullString `json:"occasion_name"`
	ID               uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, updateImage,
		arg.Published,
		arg.DateType,
		arg.ExactDate,
		arg.StartDate,
		arg.EndDate,
		arg.OccasionCategory,
		arg.OccasionName,
		arg.ID,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.OriginalFilename,
		&i.ThumbnailKey,
		&i.WebKey,
		&i.OriginalKey,
		&i.ThumbnailSize,
		&i.WebSize,
		&i.OriginalSize,
		&i.Width,
		&i.Height,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Published,
		&i.ModerationStatus,
		&i.DateType,
		&i.ExactDate,
		&i.StartDate,
		&i.EndDate,
		&i.ApproxYear,
		&i.ApproxMonth,
		&i.OccasionCategory,
		&i.OccasionName,
		&i.Exif,
	)
	return i, err
}
