// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Image struct {
	ID               uuid.UUID             `json:"id"`
	ImageID          string                `json:"image_id"`
	OriginalFilename sql.NullString        `json:"original_filename"`
	ThumbnailKey     sql.NullString        `json:"thumbnail_key"`
	WebKey           sql.NullString        `json:"web_key"`
	OriginalKey      sql.NullString        `json:"original_key"`
	ThumbnailSize    sql.NullInt64         `json:"thumbnail_size"`
	WebSize          sql.NullInt64         `json:"web_size"`
	OriginalSize     sql.NullInt64         `json:"original_size"`
	Width            sql.NullInt32         `json:"width"`
	Height           sql.NullInt32         `json:"height"`
	UploadedBy       uuid.NullUUID         `json:"uploaded_by"`
	UploadedAt       time.Time             `json:"uploaded_at"`
	Published        bool                  `json:"published"`
	ModerationStatus string                `json:"moderation_status"`
	DateType         sql.NullString        `json:"date_type"`
	ExactDate        sql.NullTime          `json:"exact_date"`
	StartDate        sql.NullTime          `json:"start_date"`
	EndDate          sql.NullTime          `json:"end_date"`
	ApproxYear       sql.NullInt32         `json:"approx_year"`
	ApproxMonth      sql.NullInt32         `json:"approx_month"`
	OccasionCategory sql.NullString        `json:"occasion_category"`
	OccasionName     sql.NullString        `json:"occasion_name"`
	Exif             pqtype.NullRawMessage `json:"exif"`
}

type ImagePerson struct {
	ID      uuid.UUID `json:"id"`
	ImageID uuid.UUID `json:"image_id"`
	Name    string    `json:"name"`
}

type ImageTag struct {
	ImageID uuid.UUID `json:"image_id"`
	TagID   uuid.UUID `json:"tag_id"`
}

type MagicLinkToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
}

type Tag struct {
	ID         uuid.UUID     `json:"id"`
	Name       string        `json:"name"`
	UsageCount int32         `json:"usage_count"`
	CreatedAt  time.Time     `json:"created_at"`
	CreatedBy  uuid.NullUUID `json:"created_by"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	Email       string         `json:"email"`
	Name        sql.NullString `json:"name"`
	Role        string         `json:"role"`
	Status      string         `json:"status"`
	InvitedBy   uuid.NullUUID  `json:"invited_by"`
	CreatedAt   time.Time      `json:"created_at"`
	LastLoginAt sql.NullTime   `json:"last_login_at"`
}
