// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddImageTag(ctx context.Context, arg AddImageTagParams) error
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	CreateImagePerson(ctx context.Context, arg CreateImagePersonParams) (ImagePerson, error)
	CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementTagUsage(ctx context.Context, id uuid.UUID) error
	DeleteImage(ctx context.Context, id uuid.UUID) error
	DeleteImagePeople(ctx context.Context, imageID uuid.UUID) error
	GetImageByID(ctx context.Context, id uuid.UUID) (Image, error)
	GetImageByImageID(ctx context.Context, imageID string) (Image, error)
	GetMagicLinkTokenByHash(ctx context.Context, tokenHash string) (MagicLinkToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	IncrementTagUsage(ctx context.Context, id uuid.UUID) error
	ListImagePeople(ctx context.Context, imageID uuid.UUID) ([]ImagePerson, error)
	ListImageTags(ctx context.Context, imageID uuid.UUID) ([]Tag, error)
	ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkTokenUsed(ctx context.Context, id uuid.UUID) error
	RemoveImageTag(ctx context.Context, arg RemoveImageTagParams) error
	SearchTags(ctx context.Context, query sql.NullString) ([]Tag, error)
	UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
