// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addImageTag = `-- name: AddImageTag :exec
INSERT INTO image_tags (image_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddImageTagParams struct {
	ImageID uuid.UUID `json:"image_id"`
	TagID   uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddImageTag(ctx context.Context, arg AddImageTagParams) error {
	_, err := q.db.ExecContext(ctx, addImageTag, arg.ImageID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, created_by)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, usage_count, created_at, created_by
`

type CreateTagParams struct {
	Name      string        `json:"name"`
	CreatedBy uuid.NullUUID `json:"created_by"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.CreatedBy)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UsageCount,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const decrementTagUsage = `-- name: DecrementTagUsage :exec
UPDATE tags SET usage_count = GREATEST(0, usage_count - 1) WHERE id = $1
`

func (q *Queries) DecrementTagUsage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementTagUsage, id)
	return err
}

const incrementTagUsage = `-- name: IncrementTagUsage :exec
UPDATE tags SET usage_count = usage_count + 1 WHERE id = $1
`

func (q *Queries) IncrementTagUsage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementTagUsage, id)
	return err
}

const listImageTags = `-- name: ListImageTags :many
SELECT t.id, t.name, t.usage_count, t.created_at, t.created_by FROM tags t
JOIN image_tags it ON it.tag_id = t.id
WHERE it.image_id = $1
ORDER BY t.name
`

func (q *Queries) ListImageTags(ctx context.Context, imageID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listImageTags, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UsageCount,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, usage_count, created_at, created_by FROM tags ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UsageCount,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeImageTag = `-- name: RemoveImageTag :exec
DELETE FROM image_tags WHERE image_id = $1 AND tag_id = $2
`

type RemoveImageTagParams struct {
	ImageID uuid.UUID `json:"image_id"`
	TagID   uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveImageTag(ctx context.Context, arg RemoveImageTagParams) error {
	_, err := q.db.ExecContext(ctx, removeImageTag, arg.ImageID, arg.TagID)
	return err
}

const searchTags = `-- name: SearchTags :many
SELECT id, name, usage_count, created_at, created_by FROM tags
WHERE name ILIKE '%' || $1 || '%'
ORDER BY usage_count DESC
LIMIT 10
`

func (q *Queries) SearchTags(ctx context.Context, query sql.NullString) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, searchTags, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UsageCount,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
